### ISSUE TITLE
mawbank item tooltip doesnt say the item is removed when spending lunar coins

### ISSUE THREAD

**Issue by milkev** [SylmarDev/SpireItems#1]
i was super confused about why my maw banks seemed to randomly dissapear in my runs. i only found out that they go poof when spending lunar coins when i looked at the thunderstore page. it would be great if such a big downside was in the tooltip in game

**Comment by SylmarDev** [comment]
that's my bad, I'll update the tooltip next commit. Thanks for pointing that out!

**Comment by SylmarDev** [comment]
just released 0.3.0 to thunderstore, with updated pickup text. Let me know if that's better 👍
