### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by GalacticRuler** [SylmarDev/SpireItems#2]
[Info   :   BepInEx] Loading [Slay The Spire Relics 0.3.1]
[Error  : Unity Log] TypeLoadException: Could not load type of field 'SylmarDev.SpireItems.Vulnerable:completeBuff' (1) due to: Could not resolve type with token 01000011 (from typeref, class/assembly R2API.CustomBuff, R2API, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:R2API, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null type:R2API.CustomBuff member:(null) signature:<none>
Stack trace:
Rethrow as TypeInitializationException: The type initializer for 'SylmarDev.SpireItems.SpireItems' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
FlashWindow:.cctor()

[Error  : Unity Log] TypeLoadException: Could not load type of field 'SylmarDev.SpireItems.Vulnerable:completeBuff' (1) due to: Could not resolve type with token 01000011 (from typeref, class/assembly R2API.CustomBuff, R2API, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:R2API, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null type:R2API.CustomBuff member:(null) signature:<none>
Stack trace:
Rethrow as TypeInitializationException: The type initializer for 'SylmarDev.SpireItems.SpireItems' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
FlashWindow:.cctor()

**Comment by SylmarDev** [comment]
apologies it's been so long - life and all

try version 0.3.3 I just released and let me know if that works for you
