### ISSUE TITLE
No items will spawn in multiplayer if any player dies. 

### ISSUE THREAD

**Issue by ConfusedToast** [SylmarDev/SpireItems#6]
Not sure if this is a conflict with any other mods we have, there are no error logs in the console. Items simply wont spawn when chests are opened or from enemy drops with sacrifice enabled.

**Comment by SylmarDev** [comment]
Are you using the latest version? If so, then yeah that is my error and I'm sorry. I can't debug multiplayer unfortunately.

**Comment by ConfusedToast** [comment]
> 

No worries, a friend of mine wanted to use it but it is what it is. Wanted to post this to inform you regardless.

**Comment by SylmarDev** [comment]
Well what version are you using? If you're on 0.5.1 I was hoping that wouldn't happen anymore, I'll look at it when I'm off work if I can badger one of my friends to run it with me so I can maybe debug it.

**Comment by ConfusedToast** [comment]
> 

0.5.1 yes, a number of character mods and a handful of item + QoL mods as well.

**Comment by SylmarDev** [comment]
Heya, I finally got a friend to run it with and I couldn't recreate the error in 0.5.1. I'm guessing its a mod conflict or someone isn't up to date. Still, I'm sorry about that. It _should_ work if you disable Dream Catcher in config. That's my very best guess. But if you can get a stack trace and post it here I'll take another look.

**Comment by ConfusedToast** [comment]
I've been busy lately and haven't played since, thanks for actually taking the time to look into this. Sorry that I don't have any other useful information as I'm no longer stuck at home and am being super busy with work.

**Comment by SylmarDev** [comment]
I played a longer run w/ friends and it broke then, so I really don't know what it is. It's definitely on my end. Turning off dream catcher in config (just make sure everyone's config is identical) should stop it from happening. 

Which is a bummer cause I like that item concept, it's just a pain to implement. I'll let you know if I fix it definitively.

**Comment by SylmarDev** [comment]
as of v0.5.2 Dream Catcher should be fixed. It now stacks per player and is unaffected by luck. So 10 dream catchers between everyone in the lobby will be a 100% drop chance, overpowered as it may be, at least the item is salvaged and doesn't have to be config'd off all the time now. Just thought I'd let you know.
